version: "3.8"

services:
    backend:
        container_name: ssafyland_backend
        build: ./backend/
        restart: always
        environment:
          TZ: Asia/Seoul
        volumes:
          - ./data/files:/data/files
        depends_on:
          - db
        ports:
          - "8080:8080"
        networks:
          - ssafyland
    db:
        image: mysql:8
        container_name: ssafyland_db
        platform: linux/x86_64
        env_file: ./db/.env
        environment:
          TZ: Asia/Seoul
        restart: always
        volumes:
          # - ./docker/db/conf.d:/etc/mysql/conf.d
          - ./db/data:/var/lib/mysql
          - ./db/initdb.d:/docker-entrypoint-initdb.d
        ports:
          - "3306:3306"
        networks:
          - ssafyland
networks:
    ssafyland:
        driver: bridge

